[tool.poetry]
name = "django-commerce"
version = "0.1.0"
description = ""
authors = ["Vitaly Shcheglov <hallovit@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
